apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stateless-app.fullname" . }}
  labels:
    {{- include "stateless-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stateless-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
