apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stateless-app.fullname" . }}
  labels:
    {{- include "stateless-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stateless-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "stateless-app.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.containers.name }}
          image: "{{ .Values.containers.image.repository }}:{{ .Values.containers.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.containers.image.pullPolicy }}
          ports:
            - name: {{ .Values.containers.ports.name }}
              containerPort: {{ .Values.containers.ports.containerPort }}
              protocol: {{ .Values.containers.ports.protocol }}