apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stateless-app.fullname" . }}
  labels:
    {{- include "stateless-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stateless-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "stateless-app.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- range .Values.containers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default $.Values.default.imagePullPolicy }}
          ports:
            - name: {{ .ports.name }}
              containerPort: {{ .ports.containerPort }}
              protocol: {{ .ports.protocol }}
          {{- if .probes.liveness.enabled | default true }}
          livenessProbe:
            httpGet:
              path: {{ .probes.liveness.path | default $.Values.default.livelinessProbe }}
              port: deepak
          {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
        {{- end }}