apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stateless-app.fullname" . }}
  labels:
    {{- include "stateless-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  
