nameOverride: "sandy"
fullnameOverride: "sandy"
replicaCount: 2
autoscaling:
  enabled: false
podAnnotations:
  app.kubernetes.io/managed-by: Helm
podSecurityContext: 
  fsGroup: 2000
default:
  imagePullPolicy: IfNotPresent
  livelinessProbe: health/live
  readinessProbe: health/ready
containers:
  - name: nginx
    image:
      repository: nginx
      tag: "1.17.9"
    ports:
      name: http
      containerPort: 80
      protocol: TCP
    probes:
      liveness:
        enabled: true
      readiness:
        enabled: false
    resources: 
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi 
  - name: nginx2
    image:
      repository: nginx
      pullPolicy: Always
      tag: "1.17.9"
    ports:
      name: http
      containerPort: 80
      protocol: TCP
    probes:
      liveness:
        enabled: true
        path: /health
    resources: {}