nameOverride: "sandy"
fullnameOverride: "sandy"
replicaCount: 2
autoscaling:
  enabled: false
podAnnotations:
  app.kubernetes.io/managed-by: Helm
podSecurityContext: 
  fsGroup: 2000
containers:
  - name: nginx
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: "1.17.9"
    ports:
      name: http
      containerPort: 80
      protocol: TCP
    probes:
      liveness:
        path: /
        port: http 
      readiness:
        path: /
        port: http 
  - name: nginx2
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: "1.7.9"
    ports:
      name: http
      containerPort: 80
      protocol: TCP
    probes: {}