nameOverride: "sandy"
fullnameOverride: "sandy"
replicaCount: 2
autoscaling:
  enabled: false
podAnnotations:
  app.kubernetes.io/managed-by: Helm
podSecurityContext: 
  fsGroup: 2000
default:
  probes:
      liveness:
        path: /health/live
        port: http
      readiness:
        path: /health/ready
        port: http
  imagePullPolicy: IfNotPresent
containers:
  - name: nginx
    image:
      repository: nginx
      tag: "1.17.9"
    ports:
      name: http
      containerPort: 80
      protocol: TCP
    probes:
      liveness:
        path: /health
        port: http
    resources: 
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi 
  - name: nginx2
    image:
      repository: nginx
      pullPolicy: Always
      tag: "1.17.9"
    ports:
      name: http
      containerPort: 80
      protocol: TCP
    probes:
      readiness:
        path: /health
        port: http
  - name: nginx3
    image:
      repository: nginx
      pullPolicy: Always
      tag: "1.17.9"
    ports:
      name: http
      containerPort: 80
      protocol: TCP
    resources: {}